### ISSUE TITLE
endpoints should be added automatically

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-streampipes#1]
When starting fresh streampipes docker containers, the list of endpoints in StreamPipes UI needs to be manually updated (as also explained in `README.md`).

This should be automatically done by StreamPipes eg. through some service discovery or something...

**Comment by JochenLutz** [comment]
This is something that can't be done in this docker-compose setup, but has to be added in the StreamPipes Backend.

So please add this to StreamPipes' bugtracker (https://laus.fzi.de/gitlab/).

**Comment by JochenLutz** [comment]
I had an idea for a work-around: You could write a little helper script that adds the endpoints via StreamPipes REST API.

**Comment by JochenLutz** [comment]
This feature is now implemented in StreamPipes 0.5
